name: CI/CD for Docker Image Deployment

on:
  pull_request:
    types:
      - closed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build --label "commit_sha=${{ github.sha }}" -t cristinacolcha/mi-app:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push cristinacolcha/mi-app:latest
  # Trabajo 2: Desplegar en múltiples instancias EC2
  deploy:
    name: Deploy Docker Container to EC2 Instances
    runs-on: ubuntu-latest
    needs: update_docker_image

    steps:
      # Paso 1: Configurar la clave SSH
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh  # Crear el directorio .ssh si no existe
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa  # Guardar la clave SSH en el archivo id_rsa
          chmod 600 ~/.ssh/id_rsa  # Asegurar que la clave privada tenga los permisos correctos

      # Paso 2: Desplegar en múltiples instancias EC2
      - name: Deploy to EC2 Instance 1
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_INSTANCE_3 }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            docker stop html-container || true
            docker rm html-container || true
            docker pull dayanara1898/html-project:latest
            docker run -d --name html-container -p 80:80 dayanara1898/html-project:latest

      - name: Deploy to EC2 Instance 2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_INSTANCE_4 }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            docker stop html-container || true
            docker rm html-container || true
            docker pull dayanara1898/html-project:latest
            docker run -d --name html-container -p 80:80 dayanara1898/html-project:latest
